services:
  frontend:
    image: ghcr.io/seancraven/typing-v2/frontend:latest
    environment:
      BE_URL: "http://backend:8080"
      SECRET_DIR: /app/secret
      HOST: "programtype.com"
    ports:
      - 443:3000
      - 80:3000
    cpus: 1
    volumes:
      - /mnt/secret/:/app/secret/
    entrypoint:
      - /bin/sh
      - -c
      - |
        npm run start
  backend:
    cpus: 1
    image: ghcr.io/seancraven/typing-v2/backend:latest
    environment:
      DATABASE_URL: sqlite:///mnt/database.db
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      RUST_LOG: INFO
    ports:
      - 8080:8080
    volumes:
      - db:/mnt/
volumes:
  db:
