services:
  backend:
    build:
      context: .
    working_dir: /project-package
    ports:
      - 8080:80
      - 3000:3000
  postgres:
    image: postgres:16-bullseye
    shm_size: 128m
    volumes:
      - /mnt/database:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
