services:
  frontend:
    build:
      context: rmx_fe
      dockerfile: Dockerfile
    environment:
      BE_URL: "http://backend:8080"
    ports:
      - 3000:3000
      - 3010:3010
    cpus: 1
    volumes:
      - ./rmx_fe/app:/app/app
    entrypoint:
      - /bin/sh
      - -c
      - |
        npm run dev
  backend:
    cpus: 1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: sqlite:///mnt/database.db
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      RUST_LOG: INFO
    ports:
      - 8080:8080
    volumes:
      - ./:/mnt/
