services:
  frontend:
    build:
      context: rmx_fe
    environment:
      BE_URL: "http://backend:8080"
      SECRET_DIR: /app/secret
      PORT: 3000
    ports:
      - 443:3000
      - 80:3000
      - 3010:3010
    cpus: 1
    volumes:
      - ./terraform/secret/:/app/secret/
      - ./rmx_fe/app/:/app/app/
    entrypoint:
      - /bin/sh
      - -c
      - |
        npm run dev
  backend:
    cpus: 1
    build:
      context: backend
    image: ghcr.io/seancraven/typing-v2/backend:latest
    environment:
      DATABASE_URL: sqlite:///data/database.db
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      RUST_LOG: INFO
    entrypoint:
      - /bin/sh
      - -c
      - |
        /usr/local/bin/typing2
    ports:
      - 8080:8080
    volumes:
      - db:/data/
volumes:
  db:
