name: Build and Push Backend Docker Image

on:
  pull_request: # Optional: Trigger on pull requests
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend Docker image
        id: build-push
        uses: docker/build-push-action@v6
        with:
          push: true
          target: linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/backend:latest
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend Docker image
        id: build-push
        uses: docker/build-push-action@v6
        with:
          push: true
          target: linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/frontend:latest
          context: rmx_fe
          cache-from: type=gha
          cache-to: type=gha,mode=max
